id: PB617E4F0
initial_creation_type: input
source_metadata:
  title: Fifth Dzogchen Rinpoche
  language: en
  description: 'Texts by and about the Fifth Dzogchen Rinpoche, Thupten Chökyi Dorje
    (rdzogs chen thub bstan chos kyi rdo rje, 1872–1935):'
  volume:
    f259d95d1aff43afb499adcd280da5e3:
      title: Brief Offering Prayer to Durtrö Lhamo, Mistress of the Charnel Ground
      parent: Dharma Protectors
    f83a9ad33c4549a6aa905e4b5a2dc373:
      title: Brief Protectors Practice
      parent: Dharma Protectors
    bb7188dce4da459dbf9291bbe27de6bc:
      title: Fulfilment Offering for Nyangrel Nyima Özer's Treasure Practice of Black
        Hayagrīva with an Iron Sword
      parent: Hayagrīva
    bbf2834d0e254701afadd807985d40c3:
      title: 'The Swift Fulfilment of Wishes: A Prayer for the Swift Return of the
        Supreme Tulku of the Fifth Drubwang Dzogchen Rinpoche'
      parent: Swift Rebirth Prayers
created_at: '2022-02-28T23:15:06.344984'
last_modified_at: '2022-02-28T23:15:06.344990'
